url: ""
plugins:
  - jekyll-sitemap
  - github-pages

defaults:
  -
    scope:
      path: ""
    values:
      layout: "view"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      permalink: /:collection/:name
      
collections_dir: _data
collections:
  projects:
    output: true

sass:
  style: compressed
